# SPDX-License-Identifier: Apache-2.0

MCU_BSP_APP_QOS_PATH := $(MCU_BSP_BUILD_CURDIR)

COMMON_FLAGS += -DMCU_BSP_SUPPORT_APP_QOS=1

VPATH += $(MCU_BSP_APP_QOS_PATH)
INCLUDES += -I$(MCU_BSP_APP_QOS_PATH)

SRCS += temporal_qos.c
