MCU_BSP_APP_TURN_JUDGE_PATH := $(MCU_BSP_BUILD_CURDIR)

COMMON_FLAGS += -DMCU_BSP_SUPPORT_APP_TURN_JUDGE=1

VPATH += $(MCU_BSP_APP_TURN_JUDGE_PATH)
INCLUDES += -I$(MCU_BSP_APP_TURN_JUDGE_PATH)

SRCS += turnJudgeTask.c
SRCS += ttc.c