MCU_BSP_APP_TIME_SYNC_PATH := $(MCU_BSP_BUILD_CURDIR)

# Flags
COMMON_FLAGS += -DMCU_BSP_SUPPORT_APP_TIME_SYNC=1

# Paths
VPATH += $(MCU_BSP_APP_TIME_SYNC_PATH)

# Includes
INCLUDES += -I$(MCU_BSP_APP_TIME_SYNC_PATH)

# Sources
SRCS += time_sync.c